# =============================================================================
# Comparison of mcrA taxonomy databases — set 4
#
#   DB1 : yang_2014_taxize.fasta        (Yang et al. 2014 — externally provided;
#                                         generated by build_mcrA_db_ncbi_annot.R)
#   DB2 : mcrA_ncbi_nt_db.fasta         (updated DB pre-curation)
#   DB3 : mcrA_ncbi_nt_cur_db.fasta     (updated DB cur. annot.)
#   DB4 : mcrA_ncbi_genome_db.fasta     (NCBI genome annotation-based DB)
#
# All databases in DADA2 format: >Domain;Phylum;Class;Order;Family;Genus;Species;Acc
#
# yang_2014_taxize.fasta must be present in the working directory before running
# this script.  It is produced by build_mcrA_db_ncbi_annot.R (Step 9).
#
# All input databases are expected to use current nomenclature (yang_2014_taxize.fasta
# is manually curated; the other databases are built with normalisation applied at
# source in build_mcrA_db_ncbi_annot.R Step 9).
# Underscores in taxonomy strings are replaced with spaces for display.
# "uncultured*" / "Unclassified" strings are treated as unresolved.
# =============================================================================

library(tidyverse)
library(ggplot2)
library(patchwork)
library(scales)
library(ggvenn)     # install.packages("ggvenn") if needed
library(pheatmap)   # install.packages("pheatmap") if needed
library(vegan)      # install.packages("vegan") if needed

setwd(dirname(rstudioapi::getSourceEditorContext()$path))

# ── File paths ─────────────────────────────────────────────────────────────────
yang_file    <- "yang_2014_taxize.fasta"       # Yang et al. 2014 — must be pre-built externally
dada2_file   <- "mcrA_ncbi_nt_db.fasta"
curated_file <- "mcrA_ncbi_nt_cur_db.fasta"
ncbi_file    <- "mcrA_ncbi_genome_db.fasta"

# ── Input validation ───────────────────────────────────────────────────────────
for (.f in c(yang_file, dada2_file, curated_file, ncbi_file)) {
  if (!file.exists(.f))
    stop(sprintf("Required input file not found: %s", .f))
}
rm(.f)

RANKS <- c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species")

# Colour palette (5 databases)
DB_COLS <- c(
  "Yang et al. 2014"        = "#d6604d",
  "updated DB"         = "#74add1",
  "updated DB cur. annot." = "#2166ac",
  "NCBI genome mcrA"    = "#984ea3"
)

DB_ORDER <- c("Yang et al. 2014", "updated DB", "updated DB cur. annot.", "NCBI genome mcrA")

UNRESOLVED_REGEX <- "^(Unclassified|unclassified|uncultured|NA|)$|^uncultured|_unclassified$"

is_resolved <- function(x) {
  !is.na(x) & x != "" & !str_detect(x, UNRESOLVED_REGEX)
}

# =============================================================================
# 1. LOAD & PARSE ALL DATABASES
# =============================================================================

# ── Helper: parse FASTA headers with semicolon-delimited taxonomy ─────────────
parse_fasta_tax <- function(fasta_path, db_label, has_taxonomy = TRUE) {
  lines        <- readLines(fasta_path)
  header_lines <- lines[str_starts(lines, ">")]
  headers      <- str_remove(header_lines, "^>") %>% str_remove(";$")

  if (!has_taxonomy) {
    # Template file: accession IDs only — fill all ranks with NA
    df <- tibble(accession = headers, db = db_label)
    for (r in RANKS) df[[r]] <- NA_character_
    attr(df, "n_seqs")   <- length(headers)
    attr(df, "n_unique")  <- n_distinct(headers)
    return(df)
  }

  df <- tibble(tax_string = headers) %>%
    separate(tax_string, into = c(RANKS, "accession"),
             sep = ";", fill = "right", extra = "drop") %>%
    mutate(across(all_of(RANKS), ~trimws(str_replace_all(.x, "_", " "))),
           db = db_label)

  attr(df, "n_seqs")   <- length(headers)
  attr(df, "n_unique")  <- n_distinct(headers)
  df
}

message("Parsing databases …")
yang_tax    <- parse_fasta_tax(yang_file,    "Yang et al. 2014",        has_taxonomy = TRUE)
dada2_tax   <- parse_fasta_tax(dada2_file,   "updated DB",         has_taxonomy = TRUE)
curated_tax <- parse_fasta_tax(curated_file, "updated DB cur. annot.", has_taxonomy = TRUE)
ncbi_tax    <- parse_fasta_tax(ncbi_file,    "NCBI genome mcrA",    has_taxonomy = TRUE)

all_dbs <- list(
  "Yang et al. 2014"        = yang_tax,
  "updated DB"         = dada2_tax,
  "updated DB cur. annot." = curated_tax,
  "NCBI genome mcrA"    = ncbi_tax
)

n_seqs_vec  <- sapply(all_dbs, function(d) attr(d, "n_seqs"))
n_uniq_vec  <- sapply(all_dbs, function(d) attr(d, "n_unique"))

for (nm in names(all_dbs)) {
  message(sprintf("  %-20s : %6d seqs  |  %6d unique paths",
                  nm, n_seqs_vec[nm], n_uniq_vec[nm]))
}

# =============================================================================
# 2. RESOLUTION RATES (counts + percentages)
# =============================================================================
resolution_rate <- function(df, db_label) {
  n_total <- nrow(df)
  map_dfr(RANKS, \(r) {
    n_res <- sum(is_resolved(df[[r]]))
    tibble(db           = db_label,
           rank         = r,
           n_total      = n_total,
           n_resolved   = n_res,
           pct_resolved = if (n_total > 0) n_res / n_total * 100 else 0)
  })
}

res_all <- map_dfr(names(all_dbs), ~ resolution_rate(all_dbs[[.x]], .x)) %>%
  mutate(rank = factor(rank, levels = RANKS),
         db   = factor(db,   levels = DB_ORDER),
         label = sprintf("%s\n(%.0f%%)", comma(n_resolved), pct_resolved))

# =============================================================================
# 3. TAXONOMIC BREADTH (unique named taxa per rank)
# =============================================================================
count_unique_taxa <- function(df, db_label) {
  map_dfr(RANKS, \(r) {
    vals  <- df[[r]]
    named <- vals[is_resolved(vals)]
    tibble(db       = db_label,
           rank     = r,
           n_unique = n_distinct(named))
  })
}

breadth_all <- map_dfr(names(all_dbs), ~ count_unique_taxa(all_dbs[[.x]], .x)) %>%
  mutate(rank = factor(rank, levels = RANKS),
         db   = factor(db,   levels = DB_ORDER))

# =============================================================================
# 4. DATABASE SIZE TABLE
# =============================================================================
size_df <- tibble(
  db     = factor(DB_ORDER, levels = DB_ORDER),
  n_seqs = n_seqs_vec[DB_ORDER],
  n_uniq = n_uniq_vec[DB_ORDER]
) %>%
  mutate(pct_of_largest = n_seqs / max(n_seqs) * 100,
         label = sprintf("%s\n(%.1f%%)", comma(n_seqs), pct_of_largest))

# =============================================================================
# 5. PAIRWISE GENUS OVERLAP WITH YANG 2014
# =============================================================================
named_taxa <- function(df, rank_col) {
  df %>% filter(is_resolved(.data[[rank_col]])) %>%
    pull(.data[[rank_col]]) %>% unique() %>% sort()
}

yang_genera <- named_taxa(yang_tax, "Genus")

overlap_vs_yang <- map_dfr(
  setdiff(DB_ORDER, "Yang et al. 2014"),   # compare each non-Yang DB against Yang et al. 2014
  function(db_label) {
    db_genera <- named_taxa(all_dbs[[db_label]], "Genus")
    tibble(
      db          = db_label,
      n_total     = length(db_genera),
      n_shared    = length(intersect(db_genera, yang_genera)),
      n_db_only   = length(setdiff(db_genera,  yang_genera)),
      n_yang_only = length(setdiff(yang_genera, db_genera))
    )
  }
) %>% mutate(db = factor(db, levels = setdiff(DB_ORDER, "Yang et al. 2014")))

# =============================================================================
# 6. MULTI-RANK FIG2 (pie charts) AND FIG3 (top-taxa bars)
# =============================================================================
# Both figures are generated for each rank in PLOT_RANKS.
# Fig2: 4 pie charts (one per database) per rank — top 20 taxa.
# Fig3: 4 horizontal bar charts per rank — top 20 taxa, SHARED x-axis range
#       across databases so sequence counts are directly comparable.
# =============================================================================

PLOT_RANKS <- c("Phylum", "Class", "Order", "Family", "Genus")

# ── Helper: top-20 pie data (rank-generic) ────────────────────────────────────
top20_pie_data <- function(df, db_label, rank_col = "Genus") {
  counted <- df %>%
    filter(is_resolved(.data[[rank_col]])) %>%
    count(.data[[rank_col]], name = "n", sort = TRUE) %>%
    rename(taxon = 1)
  top20 <- head(counted$taxon, 20L)
  result <- counted %>%
    mutate(rank_grp = if_else(taxon %in% top20, taxon, "Other"),
           db       = db_label) %>%
    group_by(db, rank_grp) %>%
    summarise(n = sum(n), .groups = "drop") %>%
    mutate(pct = n / sum(n) * 100)
  ordered_top <- top20[top20 %in% result$rank_grp]
  result$rank_grp <- factor(result$rank_grp, levels = c(ordered_top, "Other"))
  result
}

# ── Helper: build a rank-specific colour palette (top-20 global) ──────────────
rank_palette <- function(rk) {
  all_taxa <- map_dfr(DB_ORDER, function(db_label) {
    all_dbs[[db_label]] %>%
      filter(is_resolved(.data[[rk]])) %>%
      count(.data[[rk]], sort = TRUE) %>%
      rename(taxon = 1) %>%
      mutate(db = db_label)
  }) %>%
    group_by(taxon) %>%
    summarise(n_total = sum(n), .groups = "drop") %>%
    arrange(desc(n_total))
  top20 <- head(all_taxa$taxon, 20L)
  n_col  <- length(top20)
  setNames(c(scales::hue_pal()(n_col), "grey70"),
           c(top20, "Other"))
}

# ── Helper: one pie plot (accepts external palette) ───────────────────────────
make_pie <- function(df, db_label, pal, rank_label = "taxon") {
  local_taxa <- levels(df$rank_grp)
  local_cols <- setNames(
    ifelse(local_taxa %in% names(pal), pal[local_taxa], "grey80"),
    local_taxa
  )
  local_cols["Other"] <- "grey70"
  ggplot(df, aes(x = "", y = n, fill = rank_grp)) +
    geom_col(width = 1, colour = "white", linewidth = 0.2) +
    coord_polar(theta = "y") +
    scale_fill_manual(values = local_cols, name = rank_label) +
    geom_text(aes(label = ifelse(pct >= 3, sprintf("%.0f%%", pct), "")),
              position = position_stack(vjust = 0.5), size = 2.5, colour = "white") +
    labs(title = sprintf("%s  (n=%s)", db_label, comma(sum(df$n)))) +
    theme_void(base_size = 10) +
    theme(plot.title      = element_text(hjust = 0.5, face = "bold", size = 9),
          legend.text     = element_text(size = 7),
          legend.key.size = unit(0.35, "cm"),
          legend.title    = element_text(size = 8, face = "bold"))
}

# ── Shared ggplot theme (used by make_top_bar and all plot sections below) ────
theme_db <- theme_bw(base_size = 11) +
  theme(plot.title       = element_text(face = "bold", size = 12),
        plot.subtitle    = element_text(size = 9, colour = "grey40"),
        legend.position  = "bottom",
        panel.grid.minor = element_blank())

# ── Helper: one bar plot for top-20 taxa (shared x_max) ───────────────────────
make_top_bar <- function(df, db_label, rk, x_max) {
  plot_df <- df %>%
    filter(is_resolved(.data[[rk]])) %>%
    count(.data[[rk]], name = "n", sort = TRUE) %>%
    rename(taxon = 1) %>%
    slice_head(n = 20L) %>%
    mutate(taxon = fct_reorder(taxon, n))
  ggplot(plot_df, aes(x = taxon, y = n)) +
    geom_col(fill = DB_COLS[db_label], width = 0.65) +
    geom_text(aes(label = comma(n)), hjust = -0.12, size = 2.6) +
    coord_flip() +
    scale_y_continuous(limits = c(0, x_max * 1.12), labels = comma,
                       expand = expansion(mult = c(0, 0))) +
    labs(title = db_label, x = NULL, y = "# Sequences") +
    theme_db +
    theme(plot.title  = element_text(colour = DB_COLS[db_label], face = "bold"),
          axis.text.y = element_text(size = 7))
}

# ── Build and store per-rank figure lists ─────────────────────────────────────
fig2_list <- list()   # fig2_list[[rank]] = assembled pie figure
fig3_list <- list()   # fig3_list[[rank]] = assembled bar figure

for (rk in PLOT_RANKS) {
  message(sprintf("  Building Fig2/Fig3 for rank: %s …", rk))

  # ── Fig2: pie charts ────────────────────────────────────────────────────────
  pal <- rank_palette(rk)
  pie_plots_rk <- map(DB_ORDER, function(db_label) {
    dat <- top20_pie_data(all_dbs[[db_label]], db_label, rank_col = rk)
    make_pie(dat, db_label, pal, rank_label = rk)
  })
  fig2_list[[rk]] <- wrap_plots(pie_plots_rk, ncol = 2) +
    plot_annotation(
      title    = sprintf("Top 20 %ss — all databases", rk),
      subtitle = "Slices = top 20 by sequence count; remainder = 'Other'. % shown for slices ≥ 3%.",
      theme = theme(plot.title    = element_text(size = 14, face = "bold"),
                    plot.subtitle = element_text(size = 9, colour = "grey40"))
    )

  # ── Fig3: top-taxa bars, shared x-axis ─────────────────────────────────────
  # Compute global x-axis maximum across all databases for this rank
  x_max <- max(map_dbl(DB_ORDER, function(db_label) {
    all_dbs[[db_label]] %>%
      filter(is_resolved(.data[[rk]])) %>%
      count(.data[[rk]], sort = TRUE) %>%
      slice_head(n = 1L) %>%
      pull(n) %>%
      { if (length(.) == 0L) 1L else . }
  }))

  bar_plots_rk <- map(DB_ORDER, function(db_label) {
    make_top_bar(all_dbs[[db_label]], db_label, rk, x_max)
  })
  fig3_list[[rk]] <- wrap_plots(bar_plots_rk, ncol = 2) +
    plot_annotation(
      title    = sprintf("Top 20 %ss per database (shared x-axis, max = %s)",
                         rk, comma(x_max)),
      subtitle = "X-axis range fixed across all databases for direct comparability",
      theme = theme(plot.title    = element_text(size = 14, face = "bold"),
                    plot.subtitle = element_text(size = 9, colour = "grey40"))
    )
}

# =============================================================================
# 7. PLOTS
# =============================================================================
message("Building plots …")

# ── P1: Database size (counts + % of largest in brackets) ─────────────────────
p1 <- ggplot(size_df, aes(db, n_seqs, fill = db)) +
  geom_col(width = 0.6, show.legend = FALSE) +
  geom_text(aes(label = label), vjust = -0.25, size = 3.2,
            lineheight = 0.9, fontface = "bold") +
  scale_fill_manual(values = DB_COLS) +
  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.25))) +
  labs(title    = "A  Database size",
       subtitle = "Count; % = fraction of largest database",
       x = NULL, y = "# Sequences") +
  theme_db +
  theme(axis.text.x = element_text(angle = 20, hjust = 1))

# ── P2: Taxonomy resolution — counts with % in brackets ───────────────────────
# Show resolved counts on y-axis; label each point with "N (X%)"
p2 <- ggplot(res_all, aes(rank, n_resolved, colour = db, group = db)) +
  geom_line(linewidth = 1.0) +
  geom_point(size = 3) +
  geom_text(aes(label = sprintf("%s\n(%.0f%%)", comma(n_resolved), pct_resolved)),
            vjust = -0.7, size = 2.4, show.legend = FALSE) +
  scale_colour_manual(values = DB_COLS) +
  scale_y_continuous(labels = comma, expand = expansion(mult = c(0.05, 0.3))) +
  labs(title    = "B  Taxonomy resolution",
       subtitle = "Sequences with a named (non-Unclassified) assignment; % in brackets",
       x = "Rank", y = "# Resolved sequences", colour = NULL) +
  theme_db

# ── P3: Unique named taxa per rank (breadth / richness) ───────────────────────
p3 <- ggplot(breadth_all, aes(rank, n_unique, fill = db)) +
  geom_col(position = position_dodge(0.75), width = 0.7) +
  geom_text(aes(label = comma(n_unique)),
            position = position_dodge(0.75), vjust = -0.4, size = 2.5) +
  scale_fill_manual(values = DB_COLS) +
  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.25))) +
  labs(title    = "C  Taxonomic richness",
       subtitle = "Unique named taxa at each rank per database",
       x = "Rank", y = "# Unique taxa", fill = NULL) +
  theme_db

# ── P4: Genus overlap vs Yang et al. 2014 (for the 4 FASTA databases) ────────────────
overlap_long <- overlap_vs_yang %>%
  select(db, n_shared, n_db_only, n_yang_only) %>%
  pivot_longer(c(n_shared, n_db_only, n_yang_only),
               names_to = "category", values_to = "n") %>%
  mutate(category = recode(category,
                            n_shared    = "Shared with Yang et al. 2014",
                            n_db_only   = "DB-only (not in Yang)",
                            n_yang_only = "Yang-only (not in DB)"),
         category = factor(category,
                            levels = c("Yang-only (not in DB)",
                                       "Shared with Yang et al. 2014",
                                       "DB-only (not in Yang)")))

p4 <- ggplot(overlap_long, aes(db, n, fill = category)) +
  geom_col(position = "stack", width = 0.65) +
  geom_text(aes(label = ifelse(n > 0, comma(n), "")),
            position = position_stack(vjust = 0.5),
            size = 2.8, colour = "white", fontface = "bold") +
  scale_fill_manual(values = c("Shared with Yang et al. 2014"    = "#74add1",
                                "DB-only (not in Yang)"    = "#2166ac",
                                "Yang-only (not in DB)"    = "#d6604d")) +
  scale_y_continuous(labels = comma) +
  labs(title    = "D  Genus-level overlap with Yang et al. 2014",
       subtitle = "Named genera shared with / exclusive to each database",
       x = NULL, y = "# Unique genera", fill = NULL) +
  theme_db +
  theme(axis.text.x = element_text(angle = 20, hjust = 1))

# ── P5: Richness heatmap — unique taxa per rank × database ────────────────────
p5 <- ggplot(breadth_all, aes(x = db, y = fct_rev(rank), fill = n_unique)) +
  geom_tile(colour = "white", linewidth = 0.5) +
  geom_text(aes(label = comma(n_unique)), size = 3, colour = "white", fontface = "bold") +
  scale_fill_gradientn(
    colours = c("#f7fbff", "#6baed6", "#2171b5", "#08306b"),
    name    = "# Unique taxa"
  ) +
  scale_x_discrete(position = "top") +
  labs(title    = "E  Taxonomic richness heatmap",
       subtitle = "Unique named taxa per rank × database",
       x = NULL, y = "Rank") +
  theme_db +
  theme(axis.text.x  = element_text(angle = 25, hjust = 0),
        panel.grid   = element_blank(),
        legend.position = "right")

# =============================================================================
# 8. ASSEMBLE FIGURES
# =============================================================================
message("Assembling figures …")

# fig1_overview: size | resolution / breadth | overlap | heatmap
fig1 <- (p1 | p2) / (p3 | p4) / p5 +
  plot_layout(heights = c(1, 1, 0.9)) +
  plot_annotation(
    title    = "mcrA database comparison — Overview (4 databases)",
    subtitle = paste0(
      paste(sprintf("%s: %s seqs", DB_ORDER, comma(n_seqs_vec[DB_ORDER])),
            collapse = "  |  ")
    ),
    theme = theme(plot.title    = element_text(size = 15, face = "bold"),
                  plot.subtitle = element_text(size = 9,  colour = "grey40"))
  )

# (fig2_list and fig3_list already assembled per rank above)

# =============================================================================
# 7b. VENN DIAGRAMS — shared taxa across all 4 databases (per rank)
# =============================================================================
# ggvenn supports up to 4 sets.  One Venn per rank in PLOT_RANKS showing which
# named taxa are shared or exclusive to each database.
# =============================================================================
message("Building Venn diagrams …")

fig4_list <- list()   # fig4_list[[rank]] = Venn figure

for (rk in PLOT_RANKS) {
  venn_sets <- setNames(
    map(DB_ORDER, ~ named_taxa(all_dbs[[.x]], rk)),
    DB_ORDER
  )

  # ggvenn returns a ggplot object
  p_venn <- ggvenn(
    venn_sets,
    fill_color    = unname(DB_COLS[DB_ORDER]),
    stroke_size   = 0.5,
    set_name_size = 3.8,
    text_size     = 3.2
  ) +
    labs(
      title    = sprintf("Shared %ss across all databases", rk),
      subtitle = sprintf(
        "Named (resolved) %ss only — %s",
        tolower(rk),
        paste(sprintf("%s: %d", DB_ORDER,
                      map_int(venn_sets, length)),
              collapse = "  |  ")
      )
    ) +
    theme(
      plot.title    = element_text(face = "bold", size = 13),
      plot.subtitle = element_text(size =  9, colour = "grey40")
    )

  fig4_list[[rk]] <- p_venn
}

# Assemble all ranks into a single multi-panel Venn figure
fig4_all <- wrap_plots(fig4_list, ncol = 2) +
  plot_annotation(
    title = "mcrA database comparison — Taxonomic overlap (4-way Venn)",
    subtitle = paste(PLOT_RANKS, collapse = "  ·  "),
    theme = theme(plot.title    = element_text(size = 15, face = "bold"),
                  plot.subtitle = element_text(size = 10, colour = "grey40"))
  )

# =============================================================================
# 8b. HEATMAPS — per-rank count distributions across databases
# =============================================================================
# For each rank in PLOT_RANKS, build a taxa × database count matrix, apply
# vegan::decostand(method = "range", MARGIN = 1) to min-max scale each taxon's
# counts across the database columns, then render with pheatmap.
# Colour key: blue = 0 (minimum count) → white → red = 1 (maximum count).
# Database column order is fixed (cluster_cols = FALSE); taxa rows are clustered.
# Rows where all databases share the same count (range = 0, NaN after scaling)
# are set to 0 so they appear at the blue (minimum) end of the scale.
# =============================================================================
message("Building heatmaps …")

heatmap_cols <- colorRampPalette(c("#2166ac", "white", "#d6604d"))(100)

fig5_list <- list()   # fig5_list[[rank]] = pheatmap grob (for reference)

for (rk in PLOT_RANKS) {
  message(sprintf("  Building heatmap for rank: %s …", rk))

  # ── Build taxa × database count matrix ─────────────────────────────────────
  count_list <- lapply(DB_ORDER, function(db_label) {
    all_dbs[[db_label]] %>%
      filter(is_resolved(.data[[rk]])) %>%
      count(.data[[rk]], name = "n") %>%
      rename(taxon = 1)
  })
  names(count_list) <- DB_ORDER

  all_taxa <- sort(unique(unlist(lapply(count_list, `[[`, "taxon"))))

  if (length(all_taxa) == 0L) {
    message(sprintf("  No resolved taxa for rank %s — skipping", rk))
    next
  }

  count_mat <- do.call(cbind, lapply(DB_ORDER, function(db_label) {
    m <- match(all_taxa, count_list[[db_label]]$taxon)
    ifelse(is.na(m), 0L, count_list[[db_label]]$n[m])
  }))
  rownames(count_mat) <- all_taxa
  colnames(count_mat) <- DB_ORDER

  # ── Min-max scale each row (taxon) across database columns ─────────────────
  count_norm <- vegan::decostand(count_mat, method = "range", MARGIN = 1)
  count_norm[is.nan(count_norm)] <- 0   # taxa with identical counts in all DBs

  # ── PDF dimensions: cellwidth/cellheight = 10 pt; 72 pt = 1 inch ───────────
  n_rows <- nrow(count_norm)
  n_cols <- ncol(count_norm)
  pdf_w  <- max(5, (n_cols * 10 + 280) / 72)   # cells + row labels + legend
  pdf_h  <- max(4, (n_rows * 10 + 220) / 72)   # cells + col labels + dendrogram

  fname <- sprintf("fig5_heatmap_%s.pdf", tolower(rk))
  pheatmap::pheatmap(
    count_norm,
    color         = heatmap_cols,
    breaks        = seq(0, 1, length.out = 101),
    legend_breaks = c(0, 1),
    legend_labels = c("min", "max"),
    cellwidth     = 10,
    cellheight    = 10,
    cluster_cols  = FALSE,
    cluster_rows  = TRUE,
    border_color  = "grey80",
    main          = sprintf("%s  —  min–max scaled counts across databases", rk),
    filename      = fname,
    width         = pdf_w,
    height        = pdf_h
  )
  message(sprintf("  Saved %s  (%d taxa × %d databases)", fname, n_rows, n_cols))
}

# =============================================================================
# 9. SAVE
# =============================================================================
message("Saving figures …")

ggsave("fig1_overview.pdf", fig1, width = 12, height = 16)
ggsave("fig1_overview.png", fig1, width = 16, height = 20, dpi = 150)

# Per-rank fig2 (pies) and fig3 (top-taxa bars)
for (rk in PLOT_RANKS) {
  rk_lower <- tolower(rk)
  ggsave(sprintf("fig2_pies_%s.pdf", rk_lower), fig2_list[[rk]], width = 16, height = 14)
  ggsave(sprintf("fig2_pies_%s.png", rk_lower), fig2_list[[rk]], width = 16, height = 14, dpi = 150)
  ggsave(sprintf("fig3_top_%s.pdf",  rk_lower), fig3_list[[rk]], width = 16, height = ifelse(rk_lower %in% c("genus","family"),14,ifelse(rk_lower %in% c("order"),11,ifelse(rk_lower %in% c("class"),7,4))))
  ggsave(sprintf("fig3_top_%s.png",  rk_lower), fig3_list[[rk]], width = 16, height = 14, dpi = 150)
  ggsave(sprintf("fig4_venn_%s.pdf", rk_lower), fig4_list[[rk]], width = 10, height =  9)
  ggsave(sprintf("fig4_venn_%s.png", rk_lower), fig4_list[[rk]], width = 10, height =  9, dpi = 150)
  message(sprintf("  Saved fig2/fig3/fig4 for rank: %s", rk))
}

# Combined multi-rank Venn (all 5 ranks on one page)
n_ranks   <- length(PLOT_RANKS)
venn_rows <- ceiling(n_ranks / 2)
ggsave("fig4_venn_all_ranks.pdf", fig4_all,
       width = 16, height = venn_rows * 8)
ggsave("fig4_venn_all_ranks.png", fig4_all,
       width = 16, height = venn_rows * 8, dpi = 150)
message("  Saved fig4_venn_all_ranks.pdf / .png")

# =============================================================================
# 10. PRINTED SUMMARY
# =============================================================================
rule <- strrep("─", 72)
cat("\n", strrep("═", 72), "\n", sep = "")
cat("  mcrA DATABASE COMPARISON — 5 Databases\n")
cat(strrep("═", 72), "\n\n", sep = "")

cat("  Database sizes:\n")
for (db in DB_ORDER)
  cat(sprintf("    %-22s : %s sequences  |  %s unique paths\n",
              db, comma(n_seqs_vec[db]), comma(n_uniq_vec[db])))

cat("\n  ── Unique named taxa per rank ", rule, "\n", sep = "")
cat(sprintf("  %-10s", "Rank"))
for (db in DB_ORDER) cat(sprintf("  %15s", db))
cat("\n")
cat(sprintf("  %-10s", strrep("─",10)))
for (db in DB_ORDER) cat(sprintf("  %15s", strrep("─",14)))
cat("\n")
for (r in RANKS) {
  cat(sprintf("  %-10s", r))
  for (db in DB_ORDER) {
    v <- breadth_all %>% filter(rank == r, db == !!db) %>% pull(n_unique)
    cat(sprintf("  %15s", if (length(v) > 0) comma(v[1]) else "—"))
  }
  cat("\n")
}

cat("\n  ── Genus overlap with Yang et al. 2014 ", rule, "\n", sep = "")
cat(sprintf("  %-22s  %8s  %10s  %10s\n",
            "Database", "Shared", "DB-only", "Yang-only"))
for (i in seq_len(nrow(overlap_vs_yang))) {
  r <- overlap_vs_yang[i, ]
  cat(sprintf("  %-22s  %8s  %10s  %10s\n",
              as.character(r$db),
              comma(r$n_shared), comma(r$n_db_only), comma(r$n_yang_only)))
}

cat("\n  Figures saved:\n")
cat("    fig1_overview.pdf / .png\n")
for (rk in PLOT_RANKS) {
  rk_lower <- tolower(rk)
  cat(sprintf("    fig2_pies_%s.pdf / .png\n", rk_lower))
  cat(sprintf("    fig3_top_%s.pdf / .png\n",  rk_lower))
  cat(sprintf("    fig4_venn_%s.pdf / .png\n", rk_lower))
  cat(sprintf("    fig5_heatmap_%s.pdf\n",     rk_lower))
}
cat("    fig4_venn_all_ranks.pdf / .png\n")
cat(strrep("═", 72), "\n\n", sep = "")
message("Done.")

